{% set name = "django-tastypie" %}
{% set version = "0.14.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-tastypie-{{ version }}.tar.gz
  sha256: 5769e997d66726babb0cbb7643ff278b994b8ca775c5a4c510dfa0f386567d50

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - ez_setup
  run:
    - python >=3.8
    - python-mimeparse >=0.1.4,!=1.5
    - python-dateutil >=2.1

test:
  imports:
    - tastypie
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-tastypie/django-tastypie
  summary: A flexible & capable API layer for Django.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
